{
  "class": "QuestPrototype",
  "identifier": "Adventure_3_Sport_9_quest_task_2",
  "group_identifier": "Adventure_3_Sport_9",
  "progress_arrow_id": "Adventure_3_Sport_9_quest",
  "disabled": 0,
  "disabled_ru": 0,
  "position": 2,
  "is_root": 1,
  "is_autostart": 0,
  "is_hidden": 1,
  "is_optional": 0,
  "title": "Q_Текст_1",
  "congratulation": "Q_Текст_2",
  "icon": "AdventureQuestIcon",
  "task_type": "Zodiac",
  "hide_quest_accomplish": 1,
  "tasks": [
    {
      "identifier": "e9789",
      "type": "autogenerated",
      "reward_classname": "Adventure_GR_3",
      "generator": "zodiac_in_guest"
    }
  ],
  "on_activate": [
    {
      "do": "reset_quest_group",
      "group": "Adventure_3_Sport_9_quest_task_2_restarter"
    },
    {
      "do": "force_send_commands"
    }
  ],
  "on_accomplish": [],
  "disable_logs": [
    "activate",
    "accomplish",
    "spoil",
    "restart"
  ],
  "id": 68360
}