{
  "class": "QuestPrototype",
  "identifier": "Adventure_3_Sport_9_tech",
  "group_identifier": "Adventure_3_Sport_9_tech",
  "disabled": 0,
  "disabled_ru": 0,
  "is_root": 1,
  "is_autostart": 1,
  "is_hidden": 1,
  "is_optional": 0,
  "title": "Q_Текст_1",
  "congratulation": "Q_Текст_2",
  "icon": "AdventureQuestIcon",
  "task_type": "Zodiac",
  "conditions": "quest=Adventure_3_Sport_9_rewards",
  "tasks": [
    {
      "identifier": "e9801",
      "type": "have_location",
      "location_index": 1
    }
  ],
  "on_accomplish": [
    {
      "do": "reset_autogenerated_tasks",
      "quest": "Adventure_3_Sport_9_quest_task_1"
    },
    {
      "do": "reset_autogenerated_tasks",
      "quest": "Adventure_3_Sport_9_quest_task_2"
    },
    {
      "do": "reset_autogenerated_tasks",
      "quest": "Adventure_3_Sport_9_quest_task_3"
    },
    {
      "do": "simply_finish_quest_group",
      "group": "Adventure_3_Sport_9",
      "conditions": "done_quest=Adventure_3_Sport_9_rewards"
    },
    {
      "do": "spoil_quest_group",
      "group": "Adventure_3_Sport_9",
      "conditions": "done_quest!=Adventure_3_Sport_9_rewards"
    },
    {
      "do": "spoil_quest_group",
      "group": "Adventure_3_Sport_9_quest_task_1_restarter"
    },
    {
      "do": "spoil_quest_group",
      "group": "Adventure_3_Sport_9_quest_task_2_restarter"
    },
    {
      "do": "spoil_quest_group",
      "group": "Adventure_3_Sport_9_quest_task_3_restarter"
    },
    {
      "do": "force_send_commands"
    }
  ],
  "disable_logs": [
    "activate",
    "accomplish",
    "spoil",
    "restart"
  ],
  "id": 68366
}