{
  "class": "QuestActionPrototype",
  "identifier": "action_Skip_TwoDaysTournament_2026_05_01_Competition_1_Task2",
  "action_title": "Пропустить таск 2",
  "conditions": "active_quest=TwoDaysTournament_2026_05_01_Competition_1_Task2",
  "stuff_actions": [
    {
      "do": "reset_autogenerated_tasks",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task2"
    },
    {
      "do": "reset_quest",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task2"
    },
    {
      "do": "force_send_commands"
    }
  ],
  "need_to_log": 1,
  "id" : 83706
}