{
  "class": "QuestActionPrototype",
  "identifier": "action_Free_Reset_TwoDaysTournament_2026_05_01_Competition_1_Task3",
  "action_title": "Купить таск 3",
  "conditions": "quest=TwoDaysTournament_2026_05_01_Competition_1_Task3_restarter",
  "stuff_actions": [
    {
      "do": "reset_autogenerated_tasks",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task3"
    },
    {
      "do": "reset_quest",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task3"
    },
    {
      "do": "activate_quest",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task3"
    },
    {
      "do": "force_send_commands"
    }
  ],
  "need_to_log": 1,
  "id" : 83700
}