{
  "class": "QuestActionPrototype",
  "identifier": "action_Free_Reset_TwoDaysTournament_2026_05_01_Competition_1_Task1",
  "action_title": "Купить таск 1",
  "conditions": "quest=TwoDaysTournament_2026_05_01_Competition_1_Task1_restarter",
  "stuff_actions": [
    {
      "do": "reset_autogenerated_tasks",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task1"
    },
    {
      "do": "reset_quest",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task1"
    },
    {
      "do": "activate_quest",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task1"
    },
    {
      "do": "force_send_commands"
    }
  ],
  "need_to_log": 1,
  "id" : 83698
}