{
  "class": "QuestActionPrototype",
  "identifier": "action_Reset_TwoDaysTournament_2026_05_01_Competition_1_Task1",
  "action_title": "Ускорить таск 1",
  "conditions": "active_quest!=TwoDaysTournament_2026_05_01_Competition_1_Task1",
  "open_price": "money=2",
  "stuff_actions": [
    {
      "do": "reset_autogenerated_tasks",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task1"
    },
    {
      "do": "reset_quest",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task1"
    },
    {
      "do": "activate_quest",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task1"
    },
    {
      "do": "force_send_commands"
    }
  ],
  "need_to_log": 1,
  "id" : 83702
}