{
  "class": "QuestActionPrototype",
  "identifier": "action_Free_Reset_TwoDaysTournament_2026_05_01_Competition_1_tasks",
  "action_title": "Купить все таски",
  "conditions": "active_quest=TwoDaysTournament_2026_05_01_Competition_1_Counter+done_quest=TwoDaysTournament_2026_05_01_Competition_1_Task3+done_quest=TwoDaysTournament_2026_05_01_Competition_1_Task2+done_quest=TwoDaysTournament_2026_05_01_Competition_1_Task1",
  "stuff_actions": [
    {
      "do": "reset_autogenerated_tasks",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task1"
    },
    {
      "do": "reset_quest",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task1"
    },
    {
      "do": "activate_quest",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task1"
    },
    {
      "do": "reset_autogenerated_tasks",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task2"
    },
    {
      "do": "reset_quest",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task2"
    },
    {
      "do": "activate_quest",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task2"
    },
    {
      "do": "reset_autogenerated_tasks",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task3"
    },
    {
      "do": "reset_quest",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task3"
    },
    {
      "do": "activate_quest",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task3"
    },
    {
      "do": "force_send_commands"
    }
  ],
  "need_to_log": 1,
  "id" : 83701
}