{
  "class": "QuestActionPrototype",
  "identifier": "action_Free_Reset_Adventure_3_Sport_9_quest_task_1",
  "action_title": "Купить таск 1",
  "conditions": "quest=Adventure_3_Sport_9_quest_task_1_restarter",
  "stuff_actions": [
    {
      "do": "reset_autogenerated_tasks",
      "quest": "Adventure_3_Sport_9_quest_task_1"
    },
    {
      "do": "reset_quest",
      "quest": "Adventure_3_Sport_9_quest_task_1"
    },
    {
      "do": "activate_quest",
      "quest": "Adventure_3_Sport_9_quest_task_1"
    },
    {
      "do": "force_send_commands"
    }
  ],
  "need_to_log": 1,
  "id": 68343
}