{
  "class": "QuestActionPrototype",
  "identifier": "action_Reset_Adventure_3_Sport_9_quest_task_3",
  "action_title": "Купить таск 3",
  "conditions": "active_quest!=Adventure_3_Sport_9_quest_task_3",
  "open_price": "money=1",
  "stuff_actions": [
    {
      "do": "reset_autogenerated_tasks",
      "quest": "Adventure_3_Sport_9_quest_task_3"
    },
    {
      "do": "reset_quest",
      "quest": "Adventure_3_Sport_9_quest_task_3"
    },
    {
      "do": "activate_quest",
      "quest": "Adventure_3_Sport_9_quest_task_3"
    },
    {
      "do": "force_send_commands"
    }
  ],
  "need_to_log": 1,
  "id": 68348
}