{
  "class": "QuestActionPrototype",
  "identifier": "action_Skip_Adventure_3_Sport_9_quest_task_2",
  "action_title": "Пропустить таск 2",
  "conditions": "active_quest=Adventure_3_Sport_9_quest_task_2",
  "stuff_actions": [
    {
      "do": "reset_autogenerated_tasks",
      "quest": "Adventure_3_Sport_9_quest_task_2"
    },
    {
      "do": "reset_quest",
      "quest": "Adventure_3_Sport_9_quest_task_2"
    },
    {
      "do": "force_send_commands"
    }
  ],
  "need_to_log": 1,
  "id": 68350
}