{
  "class": "QuestActionPrototype",
  "identifier": "action_Free_Reset_Adventure_3_Sport_9_quest_tasks",
  "action_title": "Купить все таски",
  "conditions": "active_quest=Adventure_3_Sport_9_rewards+done_quest=Adventure_3_Sport_9_quest_task_3+done_quest=Adventure_3_Sport_9_quest_task_2+done_quest=Adventure_3_Sport_9_quest_task_1",
  "stuff_actions": [
    {
      "do": "reset_autogenerated_tasks",
      "quest": "Adventure_3_Sport_9_quest_task_1"
    },
    {
      "do": "reset_quest",
      "quest": "Adventure_3_Sport_9_quest_task_1"
    },
    {
      "do": "activate_quest",
      "quest": "Adventure_3_Sport_9_quest_task_1"
    },
    {
      "do": "reset_autogenerated_tasks",
      "quest": "Adventure_3_Sport_9_quest_task_2"
    },
    {
      "do": "reset_quest",
      "quest": "Adventure_3_Sport_9_quest_task_2"
    },
    {
      "do": "activate_quest",
      "quest": "Adventure_3_Sport_9_quest_task_2"
    },
    {
      "do": "reset_autogenerated_tasks",
      "quest": "Adventure_3_Sport_9_quest_task_3"
    },
    {
      "do": "reset_quest",
      "quest": "Adventure_3_Sport_9_quest_task_3"
    },
    {
      "do": "activate_quest",
      "quest": "Adventure_3_Sport_9_quest_task_3"
    },
    {
      "do": "force_send_commands"
    }
  ],
  "need_to_log": 1,
  "id": 68342
}