{
  "class": "QuestPrototype",
  "identifier": "TwoDaysTournament_2026_05_01_Competition_1_Task3",
  "disabled": 1,
  "disabled_ru": 0,
  "disabled_my_mail_test": 0,
  "disabled_my_mail_test_prod": 0,
  "position": 3,
  "is_hidden": 1,
  "group_identifier": "TwoDaysTournament_2026_05_01_Competition_1",
  "progress_arrow_id": "TwoDaysTournament_2026_05_01_Tech_Magazine",
  "title": "Задание №3",
  "congratulation": "Ура! Ты справился с заданием и получаешь награду!",
  "on_activate": [
    {
      "do": "reset_quest_group",
      "group": "TwoDaysTournament_2026_05_01_Competition_1_Task3_restarter"
    },
    {
      "do": "force_send_commands"
    }
  ],
  "on_accomplish": [
    {
      "do": "save_current_amount_competition_result",
      "cid": 83664
    }
  ],
  "tasks": [
    {
      "identifier" : "e9810",
      "type": "autogenerated",
      "generator": "resource",
      "reward_classname": "TwoDaysTournament_2026_05_01_Resource_Competition"
    }
  ],
  "id" : 83672
}