{
  "class": "QuestPrototype",
  "identifier": "TwoDaysTournament_2026_05_01_Competition_1_Counter",
  "disabled": 1,
  "disabled_ru": 0,
  "group_identifier": "TwoDaysTournament_2026_05_01_Competition_1",
  "is_hidden": 1,
  "hide_quest_accomplish": 1,
  "title": "Квест для фиксации прогресса",
  "on_spoil": [
    {
      "do": "reset_autogenerated_tasks",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task1"
    },
    {
      "do": "reset_autogenerated_tasks",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task2"
    },
    {
      "do": "reset_autogenerated_tasks",
      "quest": "TwoDaysTournament_2026_05_01_Competition_1_Task3"
    }
  ],
  "tasks": [
    {
      "identifier" : "e9805",
      "type": "get_asset",
      "classname": "TwoDaysTournament_2026_05_01_Resource_Competition",
      "title": "Собери конфеты"
    }
  ],
  "id" : 83667
}